theme: jekyll-theme-minimal
title: Foundations of Bioinformatics Spring 2018
description: A demo site of students cool class work portfolio
logo: https://bioboot.github.io/bimm143_S18/assets/img/logo.png  

