---
title: "map_colors_function"
author: "Barry Grant"
date: "4/20/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Let look at the poor old function

This is the function code from Barry's student.

```{r}
# Old function
map.colors <- function (value,high.low,palette) {
  proportion <- ((value-high.low[1])/(high.low[2]-high.low[1]))
  index <- round ((length(palette)-1)*proportion)+1
  return (palette[index])
}
```

Now lets try to understand this function...

```{r}
map.colors2 <- function(x, high.low=range(x), palette=cm.colors(100)) {
  
  # Determine where in the 'hig.low' range oour values of 'x' lie.
  precent <- ((x - high.low[1]) / (high.low[2] - high.low[1]))
  
  # Where in the 'palette' vector of colors is this 'precent' 
  index <- round ( (length(palette)-1) * precent)+1
  
  return(palette[index])
}
```

## Working with our own functions

My first function

```{r}
add <- function(x, y=1) {  
    # Sum the input x and y
    x + y
}
```

Lets test our first function

```{r}
add(x=6, y=4)
```

```{r}
add( c(1:5), 20 )
```

Does this work

```{r}
#add(1, 3, 10)
```

Write my 2nd function

```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

Test my 2nd function
```{r}
rescale( 1:10 )
```

```{r}
rescale( c(1,2,NA,3,10) )

```

```{r}
rescale2 <- function(x) {
   rng <-range(x, na.rm=TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale2( c(1,2,NA,3,10) )
```


```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")

   answer <- (x - rng[1]) / (rng[2] - rng[1])
   
   print("is it me you are looking for?")

   if(plot) { 
      plot(answer, typ="b", lwd=4) 
   }
   print("I can see it in ...")
   
   return(answer)
}

```

```{r}
rescale3( c(1,2,NA,3,10), plot=TRUE )
```


## Section 2B from Class 6

```{r}
library(bio3d)

```

```{r}
s1 <- read.pdb("4AKE") 
s1
```


```{r}
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.chainA
```


```{r}
s1.b <- s1.chainA$atom$b
s1.b
```

```{r}
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
```


